language: php

php:
  - 7.1

before_script:
  - mv .env.travis .env
  - touch database/database.sqlite database/phpunit.sqlite
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate

script:
  - vendor/bin/phpunit

after_script:
  - php vendor/bin/codacycoverage clover

notifications:
  email:
    recipients:
      - alanmatkorsky@gmail.com
      - leandro.jdl@gmail.com
    on_success: change
    on_failure: change
